name: build-and-deploy

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}:latest

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image (Nginx static)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          no-cache: true
          tags: |
            ${{ env.IMAGE_NAME }}
            ghcr.io/${{ github.repository }}:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            set -euxo pipefail
            cd ${{ secrets.APP_PATH }}
            docker pull ghcr.io/${{ github.repository }}:latest
            # siapkan compose lalu up
            cat > docker-compose.yml <<'YAML'
            services:
              web:
                image: ghcr.io/${GITHUB_REPOSITORY}:latest
                container_name: vierre-web
                restart: always
                ports:
                  - "80:80"
            YAML
            docker compose down || true
            docker compose up -d
