name: build-and-deploy

on:
  push:
    branches: [ "main" ]   # jalan otomatis setiap push ke branch main

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}:latest

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # agar bisa push image ke registry GitHub
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile       # pastikan Dockerfile sudah ada di root repo kamu
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}
            ghcr.io/${{ github.repository }}:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH to VPS and deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            cd ${{ secrets.APP_PATH }}

            docker pull ${{ env.IMAGE_NAME }} || true
            docker compose pull || true
            docker compose up -d
